//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfApp3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dictionary
    {
        internal static List<Dictionary> ItemsSource;

        public int ID { get; set; }
        public string Concept { get; set; }
        public string Difinition { get; set; }
        public string Sourc { get; set; }
    }
}
